
export const STICKS = [
  "BEI.png",
  "BK.png",
  "blu_dark.png",
  "pls_stick_grigio.png",
  "pnk.png",
  "red_stick.png"
];

export const LISCIO_JARS = [
  "PLS_BABYBLUE_L.jpg",
  "pls_azznao_l.jpg",
  "pls_bei_l.jpg",
  "pls_bk_l.jpg",
  "pls_blu_opac_l.jpg",
  "pls_blucob_l.jpg",
  "pls_bluroy_l.jpg",
  "pls_brw_l.jpg",
  "pls_colorinuovi",
  "pls_cyt_l.jpg",
  "pls_frag_l.jpg",
  "pls_lil_baby_l.jpg",
  "pls_lil_l.jpg",
  "pls_mag_l.jpg",
  "pls_malva_l.jpg",
  "pls_offwh_l.jpg",
  "pls_oliva_l.jpg",
  "pls_ora_l.jpg",
  "pls_ottanio_l.jpg",
  "pls_pnk_l.jpg",
  "pls_polv_l.jpg",
  "pls_rosso_fr_l.jpg",
  "pls_rosso_l.jpg",
  "pls_rosso_opa_l.jpg",
  "pls_sab_l.jpg",
  "pls_salvia_l.jpg",
  "pls_tiff_l.jpg",
  "pls_verde_nat_l.jpg",
  "pls_verde_o_l.jpg",
  "pls_verdefluo_l.jpg",
  "pls_vio_l.jpg",
  "pls_wh_ljpg.jpg",
  "pls_yw_l.jpg"
];

export const AMM_JARS = [
  "PLS_BABYBLUE_A.jpg",
  "new 24-03-25",
  "pls_azznap_a.jpg",
  "pls_bei_a.jpg",
  "pls_bk_a.jpg",
  "pls_blucob_a.jpg",
  "pls_bluo_a.jpg",
  "pls_bluroy_a.jpg",
  "pls_brw_a.jpg",
  "pls_cyt_a.jpg",
  "pls_lilla_a.jpg",
  "pls_lillababy_a.jpg",
  "pls_mag_a.jpg",
  "pls_malva_a.jpg",
  "pls_oliva_a.jpg",
  "pls_ora_a.jpg",
  "pls_ott_a.jpg",
  "pls_ow_a.jpg",
  "pls_pnk_a.jpg",
  "pls_polv_a.jpg",
  "pls_red_a.jpg",
  "pls_redfrago_a.jpg",
  "pls_redo_a.jpg",
  "pls_rossferr _a.jpg",
  "pls_sab_a.jpg",
  "pls_salvia_a.jpg",
  "pls_tiff_a.jpg",
  "pls_verdefluo_a.jpg",
  "pls_verdenat_a.jpg",
  "pls_verdeop_a.jpg",
  "pls_vio_a.jpg",
  "pls_wh_a.jpg",
  "pls_yw_a.jpg"
];

export const GRAFICHE = [
  "A MALI ESTREMI BLU.svg",
  "A MALI ESTREMI GIALLO.svg",
  "A MIO AGIO ROSA.svg",
  "A MIO AGIO VERDE.svg",
  "ALTRI BEVI.svg",
  "ANCHE SEC ME.svg",
  "ANNI DI GIN TONIC.svg",
  "APERITIVO.svg",
  "BIONDA PERMALOSA.svg",
  "BIT DRAMATIC.svg",
  "C HO L ANSIA.svg",
  "C VO A CIORT.svg"
];
